name: タスク
description: タスクの追加用
title: "タスク："
body:
  - type: markdown
    attributes:
      value: タスク管理用のIssueです。
  - type: textarea
    id: details
    attributes:
      label: タスクの詳細
      description: タスクの詳細について、可能な限り書いてください。
      placeholder: 無理ない程度に、分かる範囲で書いてくれると嬉しいです。
      value: |
        ## Issue
        ### 関連Issue
        <!-- 関連するIssueがあれば、ここにIssue番号を記載してください。 -->
        <!-- この変更により、影響が出ることが分かっているIssueなどが該当します。 -->

        ### 派生元Issue
        <!-- 派生元のIssue(議論やバグなど)があれば、ここにIssue番号を記載してください。 -->
        <!-- 大規模なバグで、影響範囲が広い場合などに、元となるバグ報告Issueなどが該当します。 -->

        ## 目的
        <!-- そのタスクが解決する課題や目的について教えてください。 -->

        ## 完了条件
        <!-- そのタスクがどうすれば完了したと見做せるか教えてください。 -->

        ## その他
        <!-- 他に説明したいことがあれば、教えてください。 -->

        ## スクリーンショット、スケッチなど
        <!-- イメージしている動作や機能のイラスト、写真があれば添付してください。 -->
    validations:
      required: true
